magazorddw:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST')}}"
      user: "{{ env_var('DB_USER')}}"
      password: "{{ env_var('DB_PASSWORD')}}"
      port: "{{ env_var('DB_PORT')}}"
      dbname: "{{ env_var('DB_NAME')}}"
      schema: "{{ env_var('DB_SCHEMA')}}"
      threads: "{{ env_var('DB_THREADS_PROD') | int}}"
      keepalive: 0